src/main/java/org/takes/facets/auth/social/PsLinkedin.java
src/test/java/org/takes/facets/auth/social/PsLinkedinTest.java

task #12 
created class PsLinkedin for LinkedIn authentication

#12 PsLinkedin

---

src/main/java/org/takes/facets/auth/PsCookie.java
src/test/java/org/takes/facets/auth/PsCookieTest.java

task #129 
added HttpOnly flag to cookie produced by PsCookie 
updated unit test

#129 PsCookie doesn't set HttpOnly

---

src/main/java/org/takes/rs/RsWithHeader.java
src/test/java/org/takes/rs/RsWithHeaderTest.java

@yegor256  here is fix for issue #114

Pull request for issue #114 "RsWithHeader doesn't validate header correctness"

---

src/test/java/org/takes/rq/RqMultipartTest.java

Please review this pull request for the 112 issue
https://github.com/yegor256/takes/issues/112
The RqMultipartTest was missing some edge tests to cover RqMultipart 100%. I've added number of negative tests along with few missing positive tests.

Issue112 rqmultipart tests

---

src/main/java/org/takes/facets/auth/PsByFlag.java
src/main/java/org/takes/facets/auth/XeLogoutLink.java
src/main/java/org/takes/facets/auth/social/PsFacebook.java
src/main/java/org/takes/facets/auth/social/PsGithub.java
src/main/java/org/takes/facets/auth/social/PsGoogle.java
src/main/java/org/takes/facets/auth/social/PsLinkedin.java
src/main/java/org/takes/facets/auth/social/XeFacebookLink.java
src/main/java/org/takes/facets/auth/social/XeGithubLink.java
src/main/java/org/takes/facets/auth/social/XeGoogleLink.java
src/main/java/org/takes/facets/fork/FkParams.java
src/main/java/org/takes/facets/fork/FkRegex.java
src/main/java/org/takes/rq/RqHref.java
src/main/java/org/takes/rs/xe/XeLinkSelf.java
src/main/java/org/takes/tk/TkClasspath.java
src/main/java/org/takes/tk/TkFiles.java
src/main/java/org/takes/tk/TkVerbose.java
src/test/java/org/takes/rq/RqHrefTest.java

for #139 
* refactored RqHref as an interface
* created RqHref.Base which implements RqHref

#139 RqHref must be an interface

---

src/main/java/org/takes/facets/auth/PsCookie.java
src/main/java/org/takes/facets/flash/TkFlash.java
src/main/java/org/takes/facets/flash/XeFlash.java
src/main/java/org/takes/rq/RqCookies.java
src/test/java/org/takes/rq/RqCookiesTest.java

for #140
* refactored RqCookies  as an interface
* created RqCookies.Base which implement RqCookies

#140 RqCookies must be an interface

---

src/main/java/org/takes/facets/fork/FkMethods.java
src/main/java/org/takes/rq/RqMethod.java
src/main/java/org/takes/tk/TkVerbose.java
src/test/java/org/takes/rq/RqMethodTest.java

For task #137 
* refactored RqMethod as interface
* created RqMethod.Base which implements RqMethod

#137 RqMethod must be an interface

---

src/main/java/org/takes/facets/forward/package-info.java
src/main/java/org/takes/rq/RqForm.java
src/main/java/org/takes/rq/RqMultipart.java
src/test/java/org/takes/rq/RqMultipartTest.java

I refactored `RqMultipart` into an interface, and added a `Base` implementation. I followed the example set by `RqHref`. 
Fixes #138

#138 - Refactored RqMultipart into an interface, implemented by RqMultipart.Base

---

src/main/java/org/takes/rs/RsFluent.java
src/main/java/org/takes/rs/RsHTML.java
src/main/java/org/takes/rs/RsRedirect.java
src/main/java/org/takes/rs/RsText.java
src/main/java/org/takes/rs/RsVelocity.java
src/main/java/org/takes/rs/RsWithBody.java
src/main/java/org/takes/rs/RsWithCookie.java
src/main/java/org/takes/rs/RsWithHeaders.java
src/main/java/org/takes/rs/RsWithStatus.java
src/main/java/org/takes/rs/RsWithType.java
src/main/java/org/takes/rs/RsWithoutHeader.java

@davvd Please look at pull request.
Problem:  constructors in org.takes.rs package accept String
Resolution: make constructors in org.takes.rs package to accept CharSequence instead of String, for higher flexibility

Pull requst for issue #109: changed String to CharSequence

---

src/test/java/org/takes/facets/auth/codecs/CcXORTest.java

For task #44 
added unit test for CcXOR

#44 CcXOR is not tested

---

src/main/java/org/takes/rq/RqForm.java
src/test/java/org/takes/rq/RqFormTest.java

1. Refactored RqForm to interface
1. Moved RqForm implementation to RqForm.Base

Fix of #135

---

src/main/java/org/takes/facets/fork/FkAnonymous.java
src/main/java/org/takes/facets/fork/FkAuthenticated.java
src/main/java/org/takes/facets/fork/FkEncoding.java
src/main/java/org/takes/facets/fork/FkFixed.java
src/main/java/org/takes/facets/fork/FkHitRefresh.java
src/main/java/org/takes/facets/fork/FkMethods.java
src/main/java/org/takes/facets/fork/FkParams.java
src/main/java/org/takes/facets/fork/FkRegex.java
src/main/java/org/takes/facets/fork/FkTypes.java
src/main/java/org/takes/facets/fork/FkWrap.java
src/main/java/org/takes/facets/fork/Fork.java
src/main/java/org/takes/facets/fork/RsFork.java
src/main/java/org/takes/facets/fork/TkFork.java
src/main/java/org/takes/misc/Opt.java
src/test/java/org/takes/facets/fork/FkAnonymousTest.java
src/test/java/org/takes/facets/fork/FkAuthenticatedTest.java
src/test/java/org/takes/facets/fork/FkEncodingTest.java
src/test/java/org/takes/facets/fork/FkHitRefreshTest.java
src/test/java/org/takes/facets/fork/FkMethodsTest.java
src/test/java/org/takes/facets/fork/FkParamsTest.java
src/test/java/org/takes/facets/fork/FkRegexTest.java
src/test/java/org/takes/facets/fork/FkTypesTest.java

For  #187 
* created interface Opt 
* created decorator Opt.Holder 
* created Opt.Empty
* replaced Iterator<> to Opt<> in route()  for all  implementations of Fork

#187 Iterator is a wrong concept for Fork.route()

---

pom.xml
src/main/java/org/takes/facets/auth/social/PsFacebook.java
src/test/java/org/takes/facets/auth/social/PsFacebookTest.java

This PR fixes the issue https://github.com/yegor256/takes/issues/41 with the following:
1. Added one more ctor to PsFacebook (there are few problems because it is a facet on a facet)
1. Created PsFacebookTest class with unit-test for PsFacebook
1. Added one explicict maven dependency (was implicict)

Fix of #41

---

src/main/java/org/takes/http/BkTimeable.java
src/main/java/org/takes/http/FtCLI.java
src/main/java/org/takes/http/Options.java
src/test/java/org/takes/http/BkTimeableTest.java

For #94 
* created BkTimeable -  Back decorator with maximum lifetime
* created unit test for BkTimeable
* added  a new argument to FtCLI to configure this behavior from command line

#94 BkTimeable

---

src/main/java/org/takes/facets/hamcrest/RsMatchStatus.java
src/main/java/org/takes/facets/hamcrest/package-info.java
src/test/java/org/takes/facets/hamcrest/RsMatchStatusTest.java
src/test/java/org/takes/facets/hamcrest/package-info.java

RsMatchStatus matcher implemented for response status code match, org.hamcrest.TypeSafeMatcher interface implemented for this purpose #166

RsMatchStatus matcher implemented

---

src/main/java/org/takes/facets/auth/codecs/CcPlain.java
src/main/java/org/takes/facets/auth/codecs/CcStrict.java
src/test/java/org/takes/facets/auth/codecs/CcStrictTest.java

CcStrict should not touch urn() or anonymous identity. 
1. Wrapped CcStrict.appyrules with condition
1. Tested CcStrict.decode of anonymous identity

CcStrict should not touch urn() or anonymous identity

---

pom.xml
src/main/java/org/takes/facets/auth/codecs/CcAES.java
src/test/java/org/takes/facets/auth/codecs/CcAESTest.java

@davvd , implementation of AES algorithm using JCE has been done for this task #132 . Would you please review? Thanks.

#132 CcXOR is not strong enough

---

src/main/java/org/takes/facets/auth/RqAuth.java
src/main/java/org/takes/facets/fork/FkEncoding.java
src/main/java/org/takes/facets/fork/FkHitRefresh.java
src/main/java/org/takes/facets/fork/FkTypes.java
src/main/java/org/takes/rq/RqCookies.java
src/main/java/org/takes/rq/RqHeaders.java
src/main/java/org/takes/rq/RqHref.java
src/main/java/org/takes/rq/RqLengthAware.java
src/main/java/org/takes/rq/RqMultipart.java
src/main/java/org/takes/rq/RqPrint.java
src/test/java/org/takes/facets/auth/TkAuthTest.java
src/test/java/org/takes/rq/RqHeadersTest.java
src/test/java/org/takes/rq/RqLiveTest.java
src/test/java/org/takes/rq/RqMultipartTest.java

#136 RqHeaders must be an interface

---

src/main/java/org/takes/facets/hamcrest/HmRsStatus.java
src/test/java/org/takes/facets/hamcrest/HmRsStatusTest.java

RsMatchStatus matcher refactored to HmRsStatus. It is now encapsulating to another matcher #166

RsMatchStatus matcher refactored to HmRsStatus

---

src/test/java/org/takes/http/BkBasicTest.java
src/test/java/org/takes/http/BkParallelTest.java

For #220 
created unit test for BkBasic

#220 BkBasic and BkParallel are not tested

---

src/it/file-manager/pom.xml
src/main/java/org/takes/http/BkTimeable.java
src/main/java/org/takes/http/FtCLI.java
src/test/java/org/takes/http/BkTimeableTest.java

For #211 
* BkTimetable has been refactored according the task description
* The unit test implemented as integration test
* The watcher's thread will be run until it become last in its thread group.

#211 BkTimetable wrong design

---

src/main/java/org/takes/facets/fork/TkMethods.java
src/test/java/org/takes/facets/fork/TkMethodsTest.java

Implementation of https://github.com/yegor256/takes/issues/106. (TkMethods)
1. Created TkMethods decorator
1. Created test case for TkMethods

Implementation of #106 (TkMethods decorator)

---

src/main/java/org/takes/facets/auth/social/PsGithub.java
src/test/java/org/takes/facets/auth/social/PsGithubTest.java

For #42, #243
* created unit test for PsGitHub

#42 PsGithub is not tested

---

src/main/java/org/takes/misc/Concat.java
src/main/java/org/takes/rq/RqWithHeader.java
src/main/java/org/takes/rs/RsWithHeader.java
src/test/java/org/takes/misc/ConcatTest.java

For task #160, replacing List.add() usage with Concat. This PR is split from #183

#160 let's get rid of List.add() - Part 1

---

src/main/java/org/takes/facets/auth/codecs/CcGzip.java
src/test/java/org/takes/facets/auth/codecs/CcGzipTest.java

Create CcGzip codec decorator which compress and decompress data. #105  - original issue.

#105 Create CcGzip coded decorator which compress and uncompress data.

---

src/main/java/org/takes/misc/Condition.java
src/main/java/org/takes/misc/Select.java
src/main/java/org/takes/rq/RqWithoutHeader.java
src/main/java/org/takes/rs/RsWithStatus.java
src/main/java/org/takes/rs/RsWithoutHeader.java
src/test/java/org/takes/misc/SelectTest.java

For task #160, replacing List.add() usage with Select for filtering. This PR is split from #183

#160 let's get rid of List.add() - Part 2

---

src/main/java/org/takes/rs/RsWithHeaders.java

Please review this PR for #268 issue. 
It actually removes the puzzle as for the #275 defect resolution.

#268 RsWithHeaders puzzle resolution

---

src/test/java/org/takes/rq/RqWithHeaderTest.java

Fix for https://github.com/yegor256/takes/issues/251 RqWithHeaderTest tests nothing)
1. Replaced `Host` header with `X-Custom-header`

Fix for #251 (RqWithHeaderTest tests nothing)

---

src/main/java/org/takes/rs/RsWithStatus.java
src/test/java/org/takes/rs/RsWithStatusTest.java

For #276 
*  implemented concatenation and selection with the conjunction Concat and Select class to get rid of List.add() according the puzzle description 
* created unit test for `RsWithStatus`

#276 RsWithStatus.java:97-101: To implement concatenation and selection

---

src/main/java/org/takes/facets/fallback/FbStatus.java
src/test/java/org/takes/facets/fallback/FbStatusTest.java

Fixed issue #295, also added test cases for FbStatus

#295 FbStatus.Check replaced by org.takes.misc.Condition

---

pom.xml
src/main/java/org/takes/rs/RsPrettyXML.java
src/test/java/org/takes/rs/RsPrettyXMLTest.java

This is fix for https://github.com/yegor256/takes/issues/296. Added new ``` RsPrettyXML``` class and test ```RsPrettyXMLTest``` for it.

 RsPrettyXML created

---

.gitignore
src/main/java/org/takes/facets/auth/Pass.java
src/main/java/org/takes/facets/auth/PsByFlag.java
src/main/java/org/takes/facets/auth/PsChain.java
src/main/java/org/takes/facets/auth/PsCookie.java
src/main/java/org/takes/facets/auth/PsEmpty.java
src/main/java/org/takes/facets/auth/PsFake.java
src/main/java/org/takes/facets/auth/PsFixed.java
src/main/java/org/takes/facets/auth/PsLogout.java
src/main/java/org/takes/facets/auth/TkAuth.java
src/main/java/org/takes/facets/auth/social/PsFacebook.java
src/main/java/org/takes/facets/auth/social/PsGithub.java
src/main/java/org/takes/facets/auth/social/PsGoogle.java
src/main/java/org/takes/facets/auth/social/PsLinkedin.java
src/main/java/org/takes/facets/auth/social/PsTwitter.java
src/test/java/org/takes/facets/auth/PsByFlagTest.java
src/test/java/org/takes/facets/auth/PsChainTest.java
src/test/java/org/takes/facets/auth/social/PsFacebookTest.java
src/test/java/org/takes/facets/auth/social/PsGithubTest.java
src/test/java/org/takes/facets/auth/social/PsGoogleTest.java
src/test/java/org/takes/facets/auth/social/PsLinkedinTest.java

Worked on issue #278.
Implemented to return Opt.

Refactored the Pass interface. Issue #278

---

src/main/java/org/takes/rq/RqMultipart.java
src/test/java/org/takes/rq/RqMultipartTest.java

Fake RqMultipart builder implemented to help create fake multipart request while testing. #252

RqMultipart.Fake implemented

---

src/main/java/org/takes/rs/RsWithCookie.java
src/test/java/org/takes/rs/RsWithCookieTest.java

Also adapted the corresponding test.

Made RsWithCookie able to combine the given value with previous ones. #293

---

src/main/java/org/takes/facets/ret/RsReturn.java
src/main/java/org/takes/facets/ret/TkReturn.java
src/main/java/org/takes/facets/ret/package-info.java
src/test/java/org/takes/facets/ret/RsReturnTest.java
src/test/java/org/takes/facets/ret/TkReturnTest.java
src/test/java/org/takes/facets/ret/package-info.java

Fix for issue #317. Added `TkReturn` and `RsReturn` classes from netbout (with proper change of packages, copyrights and versions), created test cases.

#317 TkReturn and RsReturn

---

src/test/java/org/takes/http/BkParallelTest.java

#309: use custom thread-poll size to be sure than always have more threads available than requests in tests

#309: use custom thread-poll size

---

src/main/java/org/takes/rq/RqMultipart.java
src/test/java/org/takes/rq/RqMultipartTest.java

<code>RqMultipart.Fake </code> accepting Request as ctor. input type. String type version is removed. Issue #323

#323 RqMultipart.Fake expecting Request as ctor. input

---

src/main/java/org/takes/facets/fallback/Fallback.java
src/main/java/org/takes/facets/fallback/FbChain.java
src/main/java/org/takes/facets/fallback/FbEmpty.java
src/main/java/org/takes/facets/fallback/FbFixed.java
src/main/java/org/takes/facets/fallback/FbStatus.java
src/main/java/org/takes/facets/fallback/FbWrap.java
src/main/java/org/takes/facets/fallback/TkFallback.java
src/test/java/org/takes/facets/fallback/FbChainTest.java
src/test/java/org/takes/facets/fallback/FbStatusTest.java
src/test/java/org/takes/facets/fallback/TkFallbackTest.java

Please review this PR for #294 
It switches `Fallback.route` to use `Opt` instead of `Iterator`

294 fallbackroute should return opt

---

src/main/java/org/takes/rs/RsPrettyJSON.java
src/test/java/org/takes/rs/RsPrettyJSONTest.java

Implemented RsPrettyJSON requests at #312 .
Tests are also available.
Implementation was inspired by solution for #296, see PR #308.

Fixed #312: implemented RsPrettyJSON

---

est/takes_09_06_2015.est

This is fix for https://github.com/yegor256/takes/issues/149.

 Estimation of the project size 

---

src/main/java/org/takes/facets/auth/social/PsTwitter.java
src/test/java/org/takes/facets/auth/social/PsTwitterTest.java

#230 PsTwitterTest.java:42-47: Test to be implemented for...
@davvd please find a reviewer

#230 implemented PsTwitter test

---

src/main/java/org/takes/facets/auth/PsBasic.java
src/test/java/org/takes/facets/auth/PsBasicTest.java

Added an implementation of the Basic Authentication system. Issue #221

Added an implementation of the Basic Authentication system. Issue #221

---

src/main/java/org/takes/rq/RqHeaders.java
src/main/java/org/takes/tk/TkCORS.java
src/test/java/org/takes/rq/RqHeadersTest.java

Created new single method on RqHeaders, see details  #342

#342 Added single or default value method to RqHeaders

---

src/main/java/org/takes/rq/RqForm.java
src/test/java/org/takes/rq/RqFormTest.java

#263 Extract map method creator and make it cacheable.

#263: extract method and make cacheable

---

src/main/java/org/takes/rs/RsJSON.java
src/test/java/org/takes/rs/RsJSONTest.java

For #346 
* added a call to the JsonWriter.close() to flush the write to the underlying BAOS.
* added unit test

#346 RSJson must close the JsonWriter

---

README.md
src/main/java/org/takes/rq/RqForm.java
src/main/java/org/takes/rq/RqWithBody.java
src/test/java/org/takes/rq/RqFormTest.java
src/test/java/org/takes/rq/RqWithBodyTest.java

RqForm.Fake allows form params on constructor, please see details on #321

#321 RqForm fake created to create form request with param

---

src/main/java/org/takes/facets/auth/PsAll.java
src/test/java/org/takes/facets/auth/PsAllTest.java

Implement `PsAll`. This class is a `Pass` implementatoin that combines multiple `Pass`es. It can be entered if every underlying `Pass` can be entered.
Fixes #350

Implement PsAll

---

src/main/java/org/takes/facets/auth/social/PsGoogle.java
src/test/java/org/takes/facets/auth/social/PsGoogleTest.java

For #341 
* fixed incorrect google url
* added unit test

#341 fixed google path

---

pom.xml
src/main/java/org/takes/rs/RsPrettyXML.java
src/test/java/org/takes/rs/RsPrettyXMLTest.java

Fix for https://github.com/yegor256/takes/issues/339 (#339 RsPrettyXML is losing <!DOCTYPE html>)

#339 RsPrettyXML is losing <!DOCTYPE html>

---

src/main/java/org/takes/facets/auth/social/PsGoogle.java
src/test/java/org/takes/facets/auth/social/PsGoogleTest.java

Fixed #383. Applied provided fix.

Fixed #383

---

pom.xml
src/main/java/org/takes/http/BkReuse.java
src/test/java/org/takes/http/BkReuseTest.java

#306 unit tests for persistent connections. Tests `@Ignore`-d and puzzle for implementation prepared.

unit tests for persistent connections

---

README.md

#410: Documented Maven optional dependencies in the Readme.

#410: Documented Maven optional dependencies in the Readme

---

src/main/java/org/takes/rq/RqMethod.java
src/test/java/org/takes/facets/fork/TkMethodsTest.java
src/test/java/org/takes/rq/RqMethodTest.java

#392: RqMethod validates the HTTP request method line.

#392: RqMethod validates the HTTP request method line.

---

src/main/java/org/takes/http/MainRemote.java
src/test/java/org/takes/http/MainRemoteTest.java

#439 MainRemote modification to allow additional arguments and its unit test

#439 MainRemote should allow additional arguments to be passed

---

src/test/java/org/takes/misc/MockInputStream.java
src/test/java/org/takes/misc/StateAwareInputStream.java
src/test/java/org/takes/rs/RsXSLTTest.java

Test coverage for #441.
@davvd Please proceed with code review.

RsXSLT.consume() should close InputStream

---

src/main/java/org/takes/rs/RsPrettyXML.java
src/test/java/org/takes/rs/RsPrettyXMLTest.java

I added support of empty doctype PUBLIC and empty doctype SYSTEM to solve #400.

#400 RsPrettyXML causes NPE

---

src/main/java/org/takes/rq/RqHref.java
src/test/java/org/takes/rq/RqHrefTest.java

Issue #445 fix and todo suggestion.
@davvd Please proceed with code review.

RqHref.Base validates Request-Line format

---

src/main/java/org/takes/facets/auth/social/PsGoogle.java
src/test/java/org/takes/facets/auth/social/PsGoogleTest.java

Fix for #431: `PsGoogle` uses Google+ API to get user profile image.

Use Google+ API to get user profile image

---

src/test/java/org/takes/facets/hamcrest/HmRsHeaderTest.java

#482 refactored HmRsHeader to make assertion messages cleaner

#482 refactored HmRsHeader to make assertion messages cleaner

---

src/main/java/org/takes/facets/hamcrest/HmRsStatus.java
src/test/java/org/takes/facets/hamcrest/HmRsStatusTest.java
src/test/java/org/takes/tk/TkCORSTest.java

#481 cleaner messages in failed tests in case of using HmRsStatus

#481 cleaner messages in failed tests in case of using HmRsStatus

---

src/main/java/org/takes/rs/xe/RsXembly.java
src/test/java/org/takes/rs/xe/RsXemblyTest.java

Fix for #462: `RsXembly` can modify  DOM documents.

RsXembly can modify  DOM documents

---

src/main/java/org/takes/rq/RqHeaders.java

RqHeaders now has following methods:
```
List<String> header(CharSequence key);
Set<String> names();
```
It makes working with it more convenient.
Fixes #490

RqHeaders returns List / Set instead of Iterable

---

src/main/java/org/takes/rq/RqMultipart.java
src/test/java/org/takes/rq/RqMultipartTest.java

#498 Added Content-Length to RqMultipart parts

#498 Added Content-Length to RqMultipart parts

---

src/main/java/org/takes/http/BkBasic.java
src/test/java/org/takes/http/BkBasicTest.java

Fix for #516.
Added slashes fix + junit test for this check.
Maybe it will be nice to expose header name for future reuse.

Fix for #516 - Slashes in BkBasic

---

src/main/java/org/takes/rq/RqWithDefaultHeader.java
src/test/java/org/takes/rq/RqWithDefaultHeaderTest.java

#492 moved RqWithDefault header from Netbout to Takes + added tests

#492 moved RqWithDefault header from Netbout to Takes + added tests

---

README.md

Just a minor grammatical error in the README document, as well as a literary suggestion.

README document

---

src/main/java/org/takes/misc/Opt.java
src/main/java/org/takes/rq/RqCookies.java

There were 3 typos in email address of Dmitry Zaytsev.

Typo in author's email address

---

README.md

My apologies, there was indeed a grammatical error in the original text, but I created an error in my attempt to fix it.  This should resolve it.

Typo in attempt to correct typo

---

src/main/java/org/takes/rq/RqMultipart.java
src/main/java/org/takes/rq/TempInputStream.java
src/test/java/org/takes/rq/TempInputStreamTest.java

#254 - temp file removal and stream closure in RqMultipart

#254 - temp file removal and stream closure in RqMultipart

---

src/main/java/org/takes/facets/flash/RsFlash.java

For #540 
The goal of this PR is to improve the Javadoc in RsFlash in order to:
- describe better what is "flash mechanism"
- provide more description than just "Ctor." for constructors with Throwable - focus mainly on how exception will be converted to text
- Provide information why it's better to use default cookie name
- Fix the code samples in Javadoc - they are confusing and not compilable
- Explain when you can use it and when it is not recommended

#540: Improve Javadoc in RsFlash

---

src/test/java/org/takes/tk/TkProxyTest.java

Fixing the issue #458
Adding more tests for TkProxyTest

Adding more test cases for testing multiple http methods

---

pom.xml
src/main/java/org/takes/facets/fallback/FbLog4j.java
src/main/java/org/takes/facets/fallback/FbSlf4j.java
src/main/java/org/takes/http/BkBasic.java
src/main/java/org/takes/http/MainRemote.java
src/main/java/org/takes/http/Options.java
src/main/java/org/takes/rq/RqMultipart.java
src/main/java/org/takes/rs/RsXSLT.java
src/test/java/org/takes/tk/TkProxyTest.java

Fixed the FindBug issues with PrintWriter and OutputStreams encoding.
Fixing the issue(https://github.com/yegor256/takes/issues/574)

Solving the FindBug violations.

---

src/main/java/org/takes/facets/auth/PsByFlag.java
src/main/java/org/takes/facets/auth/codecs/CcCompact.java
src/main/java/org/takes/facets/auth/codecs/CcPlain.java
src/main/java/org/takes/facets/auth/social/PsFacebook.java
src/main/java/org/takes/facets/auth/social/PsGithub.java
src/main/java/org/takes/facets/auth/social/PsGoogle.java
src/main/java/org/takes/facets/auth/social/PsLinkedin.java
src/main/java/org/takes/facets/auth/social/PsTwitter.java
src/main/java/org/takes/facets/fork/FkHitRefresh.java
src/main/java/org/takes/http/BkParallel.java
src/main/java/org/takes/http/BkTimeable.java
src/main/java/org/takes/http/FtCLI.java
src/main/java/org/takes/http/FtRemote.java
src/main/java/org/takes/http/MainRemote.java
src/main/java/org/takes/http/Options.java
src/main/java/org/takes/misc/Href.java
src/main/java/org/takes/rq/RqCookies.java
src/main/java/org/takes/rq/RqForm.java
src/main/java/org/takes/rq/RqHeaders.java
src/main/java/org/takes/rq/RqMultipart.java
src/main/java/org/takes/rs/RsVelocity.java
src/main/java/org/takes/rs/RsWithStatus.java
src/test/java/org/takes/facets/fork/FkHitRefreshTest.java
src/test/java/org/takes/http/BkBasicTest.java
src/test/java/org/takes/http/BkParallelTest.java
src/test/java/org/takes/http/BkTimeableTest.java
src/test/java/org/takes/http/FtCLITest.java
src/test/java/org/takes/misc/HrefTest.java

Fix for #557.
* `DoNotUseThreads` removed.
* `UseConcurrentHashMap` removed.
* Migration from `ConcurrentHashMap` to `HashMap`.

PMD suppressions cleanups

---

pom.xml
src/main/java/org/takes/rq/RqMultipart.java

#582 Appveyor fails when using specific features of Java 7

---

pom.xml
src/main/java/org/takes/facets/fork/MediaType.java

Issue #606. Puzzle 558-12fc4eff. Refactoring the code according to the rule ConstructorOnlyInitializesOrCallOtherConstructors and removing warning suppression.

#606 ConstructorOnlyInitializesOrCallOtherConstructors warning suppression

---

src/main/java/org/takes/facets/fork/FkChain.java
src/main/java/org/takes/facets/fork/TkFork.java
src/test/java/org/takes/facets/fork/FkChainTest.java

Fixes for #590:
- Added `FkChain` class.
- Added corresponding unit tests.
- Simplified `TkFork` implementation by the use of `FkChain`.

#590 Added Fork chain implementation and tests

---

src/main/java/org/takes/http/BkBasic.java
src/main/java/org/takes/rq/RqHeaders.java
src/main/java/org/takes/rq/RqLive.java
src/main/java/org/takes/rs/RsPrint.java
src/test/java/org/takes/http/BkBasicTest.java

Fixing the issue(https://github.com/yegor256/takes/issues/519)
- Removed  the input stream is closing to single place.
- Make the connection alive until the stream is active.

Supporting HTTP persistent connections

---

src/test/java/org/takes/tk/TkProxyTest.java

Fixing issue(https://github.com/yegor256/takes/issues/458)
Added testing multiple http methods.
This is a re creation of the PR(https://github.com/yegor256/takes/pull/551) As the merge did not happen to master

Adding more test cases

---

src/test/java/org/takes/tk/TkProxyTest.java

Fix for #656 
The goal of this PR is to add more unit tests to TkProxyTest.

#656: Added more unit tests to TkProxyTest

---

src/main/java/org/takes/facets/auth/social/PsGoogle.java
src/test/java/org/takes/facets/auth/social/PsGoogleTest.java

#669 error message from google+ api 
I modified path to extract error message. I also updated test file.

#669 Correct extraction of error message

---

src/main/java/org/takes/rq/form/package-info.java

#694 I added links to interface description, all implementations and examples of usage.

#694 I added links to interface description, all implementations and examples of usage.

---

src/test/java/org/takes/facets/auth/social/PsLinkedinTest.java

Issue #696 
Refactored PsLinkedinTest class. Anonymous classes were transformed in named inner classes.

#696 - PsLinkedinTest - fixed PMD.ExcessiveMethodLength warning

---

src/main/java/org/takes/rs/RsPrettyJson.java
src/main/java/org/takes/rs/RsPrettyXml.java
src/main/java/org/takes/tk/TkCors.java

#692 I removed AvoidDuplicateLiterals warning suppression.

#692 AvoidDuplicateLiterals suppression

---

README.md
src/main/java/org/takes/rs/RsVelocity.java
src/test/java/org/takes/rs/RsVelocityTest.java
src/test/resources/vtl/layout.vm
src/test/resources/vtl/simple.vm

This is to use the macro #parse ("file.vm")

adding a configuration by defatul for vtl folder to use velocity parse macro

---

README.md

I tried the code and found that the <configuration> tag should be outside <executions> tag.

fix the pom code in README.md

---

src/main/java/org/takes/rs/xe/XeMillis.java
src/main/resources/org/takes/facets/flash/flash.xsl
src/main/resources/org/takes/rs/xe/memory.xsl
src/main/resources/org/takes/rs/xe/millis.xsl
src/main/resources/org/takes/rs/xe/sla.xsl
src/test/java/org/takes/rs/xe/XeMemoryTest.java
src/test/java/org/takes/rs/xe/XeMillisTest.java
src/test/java/org/takes/rs/xe/XeSlaTest.java
src/test/resources/org/takes/facets/flash/test_flash.xsl
src/test/resources/org/takes/rs/xe/test_memory.xsl
src/test/resources/org/takes/rs/xe/test_millis.xsl
src/test/resources/org/takes/rs/xe/test_sla.xsl

#733: XSL templates for sla, millis, memory and flash

---

src/main/java/org/takes/rs/RsXslt.java
src/main/resources/org/takes/facets/flash/flash.xsl
src/main/resources/org/takes/rs/xe/millis.xsl
src/main/resources/org/takes/rs/xe/sla.xsl
src/test/java/org/takes/facets/flash/XeFlashTest.java
src/test/java/org/takes/rs/RsXsltTest.java
src/test/resources/org/takes/rs/stylesheet-with-include.xsl

#735: RsXslt fixed

---

src/main/java/org/takes/facets/ret/RsReturn.java
src/test/java/org/takes/facets/ret/RsReturnTest.java

Implementation of #353 according to this [SO Thread](https://stackoverflow.com/questions/161738/what-is-the-best-regular-expression-to-check-if-a-string-is-a-valid-url)

RsReturn validate location

---

src/main/java/org/takes/facets/fork/FkAgent.java
src/main/java/org/takes/facets/fork/am/AgentMatch.java
src/main/java/org/takes/facets/fork/am/AmVersion.java
src/main/java/org/takes/facets/fork/am/VersionMatch.java
src/main/java/org/takes/facets/fork/am/package-info.java
src/test/java/org/takes/facets/fork/FkAgentTest.java

PR with implementation of #284 
Code is not so great, and requiers some guidance.
And i believe time of 30m for this task is not correct, it requires like 4 times more, and splitting into smaller subtasks
Maybe add cactoos lib to depedencies and use some text classes from threre?

#284 - FkAgent, fork based on User-Agent

---

src/main/java/org/takes/misc/Condition.java
src/test/java/org/takes/misc/SelectTest.java

Condition improvement

---

src/main/java/org/takes/facets/auth/PsCookie.java
src/main/java/org/takes/facets/flash/RsFlash.java
src/main/java/org/takes/facets/ret/RsReturn.java
src/main/java/org/takes/misc/ExpirationDate.java
src/test/java/org/takes/misc/ExpirationDateTest.java

#354 Use ExpirationDate

---

src/main/java/org/takes/facets/flash/RsFlash.java
src/test/java/org/takes/facets/flash/RsFlashTest.java

#542 Add expiration date as a parameter.

---

README.md

Document FtSecure in README #437

---

src/main/java/org/takes/tk/TkRedirect.java
src/test/java/org/takes/tk/TkRedirectTest.java

TkRedirect should carry on the query and the fragment #779

---

README.md
src/main/java/org/takes/http/Front.java

#781 Document Front interface in README.md

---

README.md

For #790: Update README.md with gradle instructions.
- Added instructions for gradle usage
- Left todo for more specific gradle configurations

For #790: Update README.md with gradle instructions.

---

README.md

For #862: Versioneye removal from `README.md`.

For #862: Removing versioneye badge.

---

src/main/java/org/takes/facets/hamcrest/HmHeader.java

As requested in #770 I removed not necessary check from `HmHeader`.

#770 removed extra condition from HmHeader

---

.rultor.yml

Rearranged architects, now @paulodamaso will be notified first about merge requests from rultor.

Rearranged architects

---

.rultor.yml
pom.xml
src/test/java/org/takes/facets/auth/codecs/CcAesTest.java
src/test/java/org/takes/facets/auth/codecs/CcSaltedTest.java
src/test/java/org/takes/facets/auth/codecs/CcStrictTest.java

For #877 added JUnit v5.

---

src/main/java/org/takes/facets/fallback/TkFallback.java

#788 
* refactored TkFallback to reduce duplication

#788 refactored TkFallback

---

status-reports/2018-12-28.md

Project report: 28/12/2018

---

src/main/java/org/takes/facets/fork/FkHitRefresh.java

Continue to remove nulls as requested in PR #802

#802 Nulls Removed - FkHitRefresh.java

---

status-reports/2019-02-19.md

Status report for 2019-02-19

---

src/it/file-manager/src/main/java/org/takes/it/fm/App.java
src/it/file-manager/src/main/java/org/takes/it/fm/Item.java
src/it/file-manager/src/main/java/org/takes/it/fm/Items.java
src/it/file-manager/src/main/java/org/takes/it/fm/RsPage.java
src/it/file-manager/src/main/java/org/takes/it/fm/TkDir.java
src/it/file-manager/src/test/java/org/takes/it/fm/AppTest.java
src/test/java/org/takes/facets/auth/social/PsGithubTest.java
src/test/java/org/takes/facets/fork/FkHitRefreshTest.java
src/test/java/org/takes/http/BkTimeableTest.java
src/test/java/org/takes/http/FtCliTest.java
src/test/java/org/takes/http/MkSocket.java
src/test/java/org/takes/misc/StateAwareInputStream.java
src/test/java/org/takes/misc/VerboseListTest.java
src/test/java/org/takes/rq/multipart/RqMtSmartTest.java
src/test/java/org/takes/tk/TkFilesTest.java
src/test/java/org/takes/tk/TkProxyTest.java

For #902, removed all transient keywords.

For #902, removed all transient keywords.

---

src/main/java/org/takes/facets/auth/PsAll.java
src/main/java/org/takes/facets/fork/TkMethods.java
src/main/java/org/takes/facets/forward/RsFailure.java
src/main/java/org/takes/misc/Transform.java
src/main/java/org/takes/misc/Utf8InputStreamReader.java
src/main/java/org/takes/misc/Utf8OutputStreamWriter.java
src/main/java/org/takes/misc/Utf8PrintStream.java
src/main/java/org/takes/rq/RqSimple.java
src/main/java/org/takes/rs/RsSimple.java

In this PR I made the classes final that are mentioned in #911.

Close some classes to inheritance #911

---

README.md

For #406 added to readme.md how to version RESTful API

For #406 added to readme.md how to version RESTful API

---

pom.xml

For #943, created jacoco profile.

For #943, created jacoco profile.

---

src/main/java/org/takes/http/Options.java
src/main/java/org/takes/misc/Utf8InputStreamContent.java
src/main/java/org/takes/misc/Utf8OutputStreamContent.java
src/main/java/org/takes/rq/RqPrint.java
src/main/java/org/takes/rs/RsPrint.java
src/main/java/org/takes/rs/RsVelocity.java
src/main/java/org/takes/rs/RsXslt.java
src/main/java/org/takes/rs/xe/RsXembly.java

As discussed with @Iprogrammerr in #904 I renamed some classes to make them more idiomatic.

Rename classes to make them more idiomatic #904

---

.travis.yml

Specifying dist for JDK8 to pass (https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038/8)

#991 Specifying Trusty image for build

---

src/test/java/org/takes/http/FtRemoteTest.java
src/test/java/org/takes/tk/TkSlf4jRemoteTest.java

This PR is for [issue/869](https://github.com/yegor256/takes/issues/869)

(#869) Fixed tests with empty response

---

status-reports/2019-12-05.md

Status report 2019-12-05

---

src/main/java/org/takes/tk/TkSlf4j.java
src/test/java/org/takes/tk/TkSlf4jTest.java

Actually it is my first opensource PR, and more like a training of Yegor's OOP style. I'll be grateful for some critics
https://github.com/yegor256/takes/issues/1002

#1002 refactor TkSlf4j

---

.rultor.yml

For #1027: updating rultor image

For #1027: updating rultor image

---

src/main/java/org/takes/facets/auth/PsToken.java
src/main/java/org/takes/facets/cookies/RqCookies.java
src/main/java/org/takes/facets/fork/FkEncoding.java
src/main/java/org/takes/facets/fork/MediaType.java
src/main/java/org/takes/facets/hamcrest/HmHeader.java
src/main/java/org/takes/misc/Equality.java
src/main/java/org/takes/misc/TransformAction.java
src/main/java/org/takes/package-info.java
src/main/java/org/takes/rq/ChunkedInputStream.java
src/main/java/org/takes/rq/RqHeaders.java
src/main/java/org/takes/rq/RqHref.java
src/main/java/org/takes/rq/RqRequestLine.java
src/main/java/org/takes/rq/RqWithHeaders.java
src/main/java/org/takes/rq/form/RqFormBase.java
src/main/java/org/takes/servlet/ResponseOf.java
src/test/java/org/takes/misc/EqualityTest.java

Replacing String.trim with Trimmed

---

src/main/java/org/takes/servlet/HttpServletResponseFake.java
src/test/java/org/takes/servlet/HttpServletResponseFakeTest.java

(#1008) Fixed HttpServletResponseFake implementation

---

pom.xml
src/main/java/org/takes/facets/fork/TkFork.java

(#1025) Updated cactoos dependency to version 0.44

---

.rultor.yml

For #1036: fixes to rultor file

For #1036: fixes to rultor file

---

.rultor.yml

For #1036: updating merge config

For #1036: updating merge config

---

.rultor.yml

For #1036: removing appveyor checks from rultor merge script

For #1036: removing appveyor checks

---

src/main/java/org/takes/rq/RqPrint.java
src/test/java/org/takes/rq/RqFakeTest.java
src/test/java/org/takes/rq/RqPrintTest.java
src/test/java/org/takes/rq/RqWithDefaultHeaderTest.java
src/test/java/org/takes/rq/RqWithHeaderTest.java

For #1055: Implement Text by RqPrint

---

.rultor.yml

For #1036: fixing rultor config, using examples from cactoos

For #1036: fixing rultor config, using examples from cactoos

---

src/main/java/org/takes/rs/BodyPrint.java
src/main/java/org/takes/rs/HeadPrint.java
src/main/java/org/takes/rs/RsPrint.java

Per #1054:
- Extract printHead to HeadPrint
- Extract printBody to BodyPrint
- Leave a puzzle to continue the work

#1054: Extract printHead and printBody from RsPrint

---

.github/workflows/build.yml
pom.xml

Per #1067:
- Borrow workflow from cactoos
- Setup jacoco 
Example:
https://github.com/andreoss/takes/runs/1300725034

For #1067: Add Github Actions workflow

---

src/main/java/org/takes/rq/multipart/CopyBytesUntilBoundary.java
src/main/java/org/takes/rq/multipart/RqMtBase.java
src/test/java/org/takes/rq/multipart/CopyBytesUntilBoundaryTest.java

For #997 :
- Create `CopyBytesUntilBoundary` to extract `copy` function
- Introduce a test to show bug

(#997) Introduce a test to show bug

---

pom.xml
src/main/java/org/takes/rs/RsPrint.java
src/test/java/org/takes/facets/auth/PsByFlagTest.java
src/test/java/org/takes/facets/auth/codecs/CcBase64Test.java
src/test/java/org/takes/facets/auth/codecs/CcCompactTest.java
src/test/java/org/takes/facets/auth/codecs/CcPlainTest.java
src/test/java/org/takes/rq/form/RqFormFakeTest.java

Per #1073 
- Remove guava as a test dependency

#1073: Remove guava

---

src/main/java/org/takes/rq/RqFake.java
src/test/java/org/takes/rq/RqFakeTest.java

- Update `RqFake`
- Update `RqFake` test
Close: #1024

(#1024) Invalid request line

---

src/main/java/org/takes/tk/TkFiles.java

Sorry, but I haven't run any tests. I'm not Java programmer, but I think this changes makes this code more Java-way.

Use `cactoos.InputOf`

---

README.md

see Templates and Content Negotiation section.

style(readme): bit typo on mention

---

src/main/java/org/takes/rs/RsXslt.java
src/test/java/org/takes/rs/RsXsltTest.java

@yegor256 Please review.
Fix for https://github.com/yegor256/takes/issues/1293
>> Takes framework has an XSLT injection vulnerability

fixed #1293 'Takes framework has an XSLT injection vulnerability'
