yegor256/takes

README.md
Following are the changes made to the documentation (https://github.com/yegor256/takes/issues/154):
In **A Bigger Example** section:
1. `ts` stands for "take"  - typo error, it should be `tk` instead of `ts`
2. In `act()` method of `TkIndex` class, there is a typo error. The class name should be `RsHTML` instead of `RsHtml`
3. In the example showing the use of `TkFork`, `act()` needs to have `throws` clause, `throws IOException`
=> Fixed issues in documentation.

src/main/java/org/takes/facets/auth/codecs/CcStrict.java, src/test/java/org/takes/facets/auth/codecs/CcStrictTest.java
task #153
Changed urn validation according with RFC 2141 in CcStrict, RFC 2141 compilant regexp took [here](https://github.com/jcabi/jcabi-urn/blob/master/src/main/java/com/jcabi/urn/URN.java#L98).
Also changed unit test
=> #153 CcStrict validation works incorrectly

.gitattributes
Issue description:
If you use operation system with default "end of line char" different from Unix/Linux (\n), and you have no default config for your git:
after checkout repository, all files will contains "standard" for you system end of line char. So build will fail with error from qulice about end of line violations if all files. 
Fix:
added git config for repository to force using Unix\Linux end of line char.
=> Fix for issue #148 - Build failed on windows with lots of EOL violations

src/main/java/org/takes/rs/RsWithCookie.java, src/test/java/org/takes/rs/RsWithCookieTest.java
For task #46 
*  Ctor parameter name validates according [RFC 2616, section 2.2](http://tools.ietf.org/html/rfc6265#section-4.1.)
*  Ctor parameter value validates according [RFC 6265 section 4.1.1](http://tools.ietf.org/html/rfc2616#section-2.2)
*  added unit tests for new functionality
=> #46 RsWithCookie must reject if invalid characters

src/main/java/org/takes/rq/RqLengthAware.java, src/test/java/org/takes/rq/RqLengthAwareTest.java
for #206 
* implemented  the other two InputStream.read() methods
=> #206 RqLengthAware doesn't intercept the other two read() methods

src/main/java/org/takes/rs/RsWithHeaders.java, src/test/java/org/takes/rs/RsWithHeadersTest.java
For #113
Got rid code duplication in RsWithHeader and RsWithHeaders according the task description
=> #113 RsWithHeaders must reuse RsWithHeader

src/main/java/org/takes/http/BkBasic.java, src/main/java/org/takes/rq/RqSocket.java, src/main/java/org/takes/rq/RqWithHeader.java, src/main/java/org/takes/rq/RqWithHeaders.java, src/test/java/org/takes/http/BkBasicTest.java, src/test/java/org/takes/rq/RqSocketTest.java, src/test/java/org/takes/rq/RqWithHeaderTest.java, src/test/java/org/takes/rq/RqWithHeadersTest.java
This is fix for https://github.com/yegor256/takes/issues/130
Added ```RqSocket``` decorator to extract socket specific information from the request. 
Edited ```BkBasic``` to inject socket specific information into request.
=>  Socket information in request

src/main/java/org/takes/misc/Transform.java, src/main/java/org/takes/misc/TransformAction.java, src/main/java/org/takes/rs/RsWithHeaders.java, src/test/java/org/takes/misc/TransformTest.java
For task #160, introducing Transform for eliminating the use of `List.add()` in `RsWithHeaders`. This PR is split from #183
=> #160 let's get rid of List.add() - Part 3

src/main/java/org/takes/facets/auth/social/PsLinkedin.java, src/test/java/org/takes/facets/auth/social/PsLinkedinTest.java
For task #239, removing request parameters in `Href` object and move them into body.
=> #239 PsLinkedin passes the request parameters to the URI.

src/main/java/org/takes/facets/auth/social/PsGoogle.java, src/test/java/org/takes/facets/auth/social/PsGoogleTest.java
For #43 
* added unit test for PsGoogle
The test's implementation is not originally proposed.
PsGoggle makes two http-request inside but FakeRequest can simulate one only. Similar case was discussed in the #42 and  @yegor256 [suggested](https://github.com/jcabi/jcabi-http/pull/83#issuecomment-97580978) to use Takes as moked OAuth server.
=> #43 PsGoogle is not tested

src/main/java/org/takes/facets/fork/FkContentType.java, src/main/java/org/takes/facets/fork/TkConsumes.java, src/test/java/org/takes/facets/fork/FkContentTypeTest.java, src/test/java/org/takes/facets/fork/TkConsumesTest.java
This is fix for https://github.com/yegor256/takes/issues/107
Added new fork ```FkContentType```, new decorator ```TkConsumes``` and required tests for it.
=> TkConsumes decorator implementation

src/main/java/org/takes/http/BkBasic.java, src/test/java/org/takes/http/BkBasicTest.java
Fix for https://github.com/yegor256/takes/issues/231 (FtRemote hides TkFork response status)
1. Wrapped failure handling at BkBasic with response code depending on exception class
1. Unit-test for response code handling
=> Fix for #231 (FtRemote hides TkFork response status)

src/test/java/org/takes/http/BkParallelTest.java
As suggested in pull request [#246](https://github.com/yegor256/takes/pull/246), implemented a test case which launches several requests from separate threads and ensures that requests are being executed in parallel
=> #227 BkParallelTest is not implemented

src/main/java/org/takes/rq/RqMultipart.java, src/main/java/org/takes/rq/RqPrint.java, src/main/java/org/takes/rs/RsPrint.java, src/main/java/org/takes/rs/RsXSLT.java
For #205 
* `RqLengthAware` is an `InputStream` implementation. It's out of the scope of the task.
* `RqLive` parses using `read()` the request header only. Usually  it has very small size. No needs to be buffered
* `RqMultipart` buffered read will be implemented in PR #255 
* `RqPrint` `read()` replaced with  `read(byte[])` 
* `RsGzip` uses `read(byte[])`  already
* `RsPrint` `read()` replaced with  `read(byte[])` 
* `RsXSLT` `read()` replaced with  `read(byte[])` 
No needs to create a new unit tests. The classes has tests already.
=> #205 stream reading is too slow 

src/main/java/org/takes/rq/RqMultipart.java, src/test/java/org/takes/rq/RqMultipartTest.java
For #248 
* made some speed optimization in RqMultipart.Base 
* java.io.*  has been replaced for java.nio.*
* parsing time for a 100mb request reduced from 14s to 1s
I used the code below to measure execution time
```
final int length = 100000000;
final long start = System.currentTimeMillis();
final Request req = new RqFake(
Arrays.asList(
"POST /post?u=3 HTTP/1.1",
"Host: www.example.com",
"Content-Type: multipart/form-data; boundary=zzz"
),
Joiner.on(RqMultipartTest.CRLF).join(
"--zzz",
"Content-Disposition: form-data; name=\"x-1\"",
"",
StringUtils.repeat("X", length),
"--zzz--"
)
);
MatcherAssert.assertThat(
new RqMultipart.Smart(
new RqMultipart.Base(req)
).single("x-1").body().available(),
Matchers.equalTo(length)
);
Logger.info(
this,
"#returnsCorrectPartLength() with length %d in …
```
=> #248 RqMultipart.Base is too slow with big requests

src/main/java/org/takes/rs/RsWithType.java, src/test/java/org/takes/rs/RsWithTypeTest.java
For #217 
RsWithType will now also use RsWithoutHeader to make sure it replaces
any previous types before adding the new one.
I also added tests for RsWithType.
As it is my first change for the team, feel free to point out anything so I can improve present and future work. Thanks.
=> Fixed RsWithType duplicating headers.

src/main/java/org/takes/rs/RsWithType.java, src/test/java/org/takes/rs/RsWithTypeTest.java
Please review this PR fixing "RsWithType overrides status code" #298
The fix actually removes passing HTTP OK status code.
=> Fix for  "RsWithType overrides status code"

src/main/java/org/takes/facets/fallback/FbStatus.java, src/test/java/org/takes/facets/fallback/FbStatusTest.java
Fix for issue #292. As discussed in issue, I'm taking a response code with explanation message from `RsWithStatus` head.
=> #292 FbStatus without second argument

src/main/java/org/takes/rs/RsText.java, src/test/java/org/takes/rs/RsTextTest.java
Changed the RsText constructor to pass the response in the parameter instead of forcing a 200 response status.
Fixes #310
=> #310 RsText maintains status code

src/main/java/org/takes/rq/RqWithHeader.java
Please review this PR fixing #257.
I've changed `RqWithHeader` to make use of `RqWithHeaders` passing singleton collection as second arg.
=> Fixed #257: changed RqWithHeader to use RqWithHeaders

src/test/java/org/takes/rq/RqMultipartTest.java
Pull request for issue #253. I simply re-enabled ignored test and ran it 1000 times locally to make sure it is working. Looks like it is already fixed by previous commits as outlined in https://github.com/yegor256/takes/issues/291#issuecomment-106116283.
=> #253 Enabled RqMultipartTest.consumesHttpRequest

src/main/java/org/takes/rq/RqMultipart.java, src/test/java/org/takes/rq/RqMultipartTest.java
For #331 
* fixed a bug with the distortion of the contents of the request if the request contains the boundary characters in some conditions
* added the unit test to check this.
=> #331 RqMultipart.Base fixed bug with the distortion of the contents

src/main/java/org/takes/rq/RqBytes.java, src/main/java/org/takes/rq/RqFake.java, src/test/java/org/takes/rq/RqFakeTest.java
#120: Two RqFake instances are equal if they contain the same head and
byte array body.
=> #120: RqFake equals()

src/main/java/org/takes/facets/hamcrest/HmRqHeader.java, src/main/java/org/takes/facets/hamcrest/HmRsHeader.java, src/test/java/org/takes/facets/hamcrest/HmRqHeaderTest.java, src/test/java/org/takes/facets/hamcrest/HmRsHeaderTest.java
Referenced to #260 issue.
Please take a look at this PR implementingHsRqHeader and HsRsHeader + relevant test.
The constructor for both accepts `final Matcher<? extends Map<? extends CharSequence, ? extends CharSequence>> mtchr)` which is different from what was originally reported, but that was already discussed with reporter. 
Additionally `Map` parametrisation was changed from `String` to `CharSequence` since it is not possible to have wild card with final `String` class.
Note the usage 
`new HmRsHeader(Matchers.hasEntry("content-encoding", "gzip"))` 
which expects lower value header name in order to work correctly.
=> Implements HsRqHeader and HsRsHeader #260

src/main/java/org/takes/Response.java, src/main/java/org/takes/rs/RsWithBody.java
#290: Enhanced javadoc for the Response class by describing the restrictions regarding the order of the head() and body() methods invocation.
=> #290: Enhanced javadoc for the Response class

src/main/java/org/takes/rs/RsWithBody.java, src/test/java/org/takes/tk/TkGzipTest.java
Fixed #286 
Changed `RsWithBody` Response creation in a way that length value is obtained from `InputStream.available` without delay, since further caller of body method mat happen to close the stream. Enabled the test.
=> 286 tkgziptest compreses on demand does not work

pom.xml, src/main/java/org/takes/facets/hamcrest/EntryMatcher.java, src/main/java/org/takes/facets/hamcrest/HmRsHeader.java, src/main/java/org/takes/misc/EntryImpl.java, src/test/java/org/takes/facets/hamcrest/HmRsHeaderTest.java
#412: Added additional constructors to HmRsHeader.
=> #412: Added additional constructors to HmRsHeader

src/main/java/org/takes/facets/hamcrest/HmRqHeader.java, src/main/java/org/takes/facets/hamcrest/HmRsHeader.java, src/test/java/org/takes/facets/hamcrest/HmRqHeaderTest.java
#413: Added additional constructors to HmRqHeader.
=> #413: Added additional constructors to HmRqHeader

src/main/java/org/takes/rs/RsXSLT.java, src/test/java/org/takes/rs/RsXSLTTest.java, src/test/resources/org/takes/rs/inclass/imported.xsl, src/test/resources/org/takes/rs/included.xsl, src/test/resources/org/takes/rs/includes.xsl
Fix for issue #450 - base parameter in RsXSLT.InClasspath.resolve(String, String) is unused.
- RsXSLT.InClasspath.resolve() method updated to use URI.resolve() for "href" when "base" parameters is not null. When "base" is null URI on href is created.
- RsXSLTTest.resolvesInClasspath() test method updated to test also xsl:include and xsl:import with relative and absolute paths.
- Added 3 .xsl files in order to test InClasspath.resolve() calls also for xsl:include & xsl:import.
=> #450 - RsXSLT.InClasspath resolve() method was not using "base" parameter.

src/main/java/org/takes/tk/TkReadAlways.java, src/test/java/org/takes/tk/TkReadAlwaysTest.java
Fix for issue #453 
- Implemented TkReadAlways Take decorator as requested. After the origin take creates the response available body() content from request is skipped using InputStream.skip() method.
- Added TkReadAlwaysTest test for the implemented decorator.
=> #453 - Connection reset if request body wasn't read from POST

src/main/java/org/takes/rs/RsXSLT.java
#450 - RsXSLT.InClasspath.resolve() method checks base parameter is checked also with ifEmpty()
=> #450 - RsXSLT.InClasspath.resolve() method cheks base parameter isEmpty()

src/test/java/org/takes/rq/RqFormTest.java, src/test/java/org/takes/rq/RqGreedyTest.java, src/test/java/org/takes/rq/RqLengthAwareTest.java, src/test/java/org/takes/rq/RqMultipartTest.java, src/test/java/org/takes/rq/RqWithBodyTest.java
Fix for ticket #463. Include Content-Length header from test requests.
=> Include Content-Length header from test requests

src/main/java/org/takes/facets/hamcrest/HmRsHeader.java, src/test/java/org/takes/facets/hamcrest/HmRsHeaderTest.java
Fix for #480. 
* Refactor `HmRsHeader` matcher to accept any header and value matchers.
* Make `IsEqualIgnoringCase` default header matcher when selecting headers by `String`.
=> Refactor HmRsHeader matcher to accept any header and value matchers

src/main/java/org/takes/rs/RsWithType.java, src/test/java/org/takes/rs/RsWithTypeTest.java
Implementing classes `RsWithType.HTML / JSON / XML / Text` to support standardized way of setting Content-Type header for those for cases as asked for in #496 .
=> Add specific RsWithType classes

pom.xml, src/main/java/org/takes/tk/TkRetry.java, src/test/java/org/takes/tk/TkRetryTest.java
Resolving #430. Nearly the same as the last suggested PR.
Added an assertion on the last test to ensure expected response is returned after the first fail.
=> TkRetry #430

src/test/java/org/takes/rq/RqFormTest.java
Fix for #463.
Add Content-Length header to `RqFormTest.createsFormRequestWithParams()`.
=> #463: add Content-Length header in RqFormTest

src/test/java/org/takes/http/BkBasicTest.java
Fix for #454
- File BkBasicTest tests updated with a mocked socket initialized properly.
The tests were moved from BkReuseTest to BkBasicTest in PR #500 ticket #456.
=> Fix for #454 - BkReuseTest does not send proper request

src/main/java/org/takes/facets/fallback/TkFallback.java, src/test/java/org/takes/facets/fallback/TkFallbackTest.java
Fix for #433:
- Updated TkFallback to check the Opt<Response> from the given fallback,
and if empty throw a message with a proper message.
- Updated TkFallbackTest to run the snippet and check if the exception has
the proper message.
=> Fix for #433 - TkFallback crashes when there is no fallback.

src/main/java/org/takes/misc/Href.java, src/test/java/org/takes/misc/HrefTest.java
For #548 
The goal of this PR is to prevent getting URISyntaxException when we have to deal with not properly encoded url. It fixes that by encoding all the invalid characters until we get a parseable URI.
=> #548: Prevent getting URISyntaxException due to bad urls by automatically fixing them

src/main/java/org/takes/rs/RsWithBody.java, src/main/java/org/takes/rs/RsWithType.java, src/test/java/org/takes/rs/RsWithTypeTest.java
For #524 
The goal of this PR is to add the charset into the content type header by using the new constructor of RsWithType allowing to explicitly specify the charset.
=> #524: Added the ability to specify the charset if needed

src/test/java/org/takes/facets/fork/FkHitRefreshTest.java, src/test/java/org/takes/http/BkTimeableTest.java, src/test/java/org/takes/rq/RqMultipartTest.java, src/test/java/org/takes/tk/TkFilesTest.java
The principal problem was in the RqMultipartTest because the requests are creating temporary files greater than 97mb, those files are now deleted after the junit test.
But, some files with 1KB stills remains in computer, I believe we need to fix the issue #576.
**- Refactoring notes**
1) Some tests was creating files not using TemporaryFolder.
2) RqMultipartTest was change to delete the temporary files after the execution of the junit. In order to that, I need the close the body part of the multipart request.
With these changes, after the execution of the all junits, the temporay files with 97mb are deleted after the junit ends, eliminating the instability of the builds. 
**This PR is related with issue #506**
**Code changes**
- RqMultipartTest - Lines 106 - 117
Without that changes the …
=> #506 BkTimeableTest fails intermittently 

src/test/java/org/takes/http/BkTimeableTest.java, src/test/java/org/takes/http/FtCLITest.java
Bug #573 Unstable Travis-CI Build. 
After increase the amount of lifetime of the ServerSocket, the unstable builds in travis doesn't occur anymore.
**List of changes**
- BkTimeableTest: Increased the lifetime of the ServerSocket to 4000ms;
- FtCLITest: Increased the lifetime of the ServerSocket to 4000ms.
=> #573 Unstable Travis-CI Build

src/main/java/org/takes/facets/auth/PsBasic.java, src/main/java/org/takes/facets/fallback/FbStatus.java, src/main/java/org/takes/facets/fork/FkEncoding.java
Bug #597. Replaces String.split(regexp), with regexp that is at least 2 character long, by private static final Pattern field.
=> #597 replaces String.split by Pattern final static field.

src/main/java/org/takes/facets/fork/MediaType.java, src/main/java/org/takes/misc/Href.java
Fix for #596.
* Refactor `String.replaceAll(`) to `Matcher.replaceAll()`.
=> Refactor String.replaceAll() to Matcher.replaceAll()

src/main/java/org/takes/rq/CapInputStream.java, src/main/java/org/takes/rq/RqMultipart.java, src/test/java/org/takes/rq/CapInputStreamTest.java
#575 is solved by this.
* Implemented `close` and `skip` on `CapInputStream`
* Added tests verifying that those actually delegate the `close` and `skip` to the stream the class wraps as requested by the Puzzle
**Caveat(?)**
* This entailed removing the finally call closing `stream` from `org.takes.rq.RqMultipart.Base#Base`! which is in line with the behavior tests like `org.takes.rq.RqMultipartTest#returnsCorrectPartLength` assume when they call the close on the `org.takes.rq.RqMultipart.Base#body` manually at the end of the test. The only reason this worked before was that closing on the `CapInputStream` did nothing but throw IOException` => no actual closing ever happened in `org.takes.rq.RqMultipart.Base`.
* This likely explains #626 and #512 I think, since `CapInputStream` wraps all …
=> #575 implement close and skip method on CapinputStream

src/test/java/org/takes/http/BkBasicTest.java, src/test/java/org/takes/http/MkSocket.java
Fix for https://github.com/yegor256/takes/issues/533:
Followed the principale described [here](http://www.yegor256.com/2014/09/23/built-in-fake-objects.html) by replacing a mock created with Mockito with an explicit mock Socket called MkSocket.
=> 533: Create explicitly a mock socket

src/main/java/org/takes/facets/fork/FkContentType.java, src/main/java/org/takes/facets/fork/TkConsumes.java, src/test/java/org/takes/facets/fork/FkContentTypeTest.java
Issue #461 - FkContentType is built with a Response. To handle more general use cases like Content-Type: text/html; charset=..., it should be built with a Take that will handle the request dynamically.
=> #461 FkContentType should have a Take rather than a Response.

src/main/java/org/takes/rq/RqMultipart.java
Issue #594 - Solving puzzle 558-afc1c081 in
src/main/java/org/takes/rq/RqMultipart.java:131-135
- The class was refactored according to this article: http://www.yegor256.com/2015/05/07/ctors-must-be-code-free.html
- Removes the warning suppression (PMD.ConstructorOnlyInitializesOrCallOtherConstructors)
- Create static methods (body(final Request req) and buffer(final Request req)) to the constructor contains only variables initialization and other constructor calls.
=> #594 RqMultipart.java - Removing the warning suppression (PMD.ConstructorOnlyInitializesOrCallOtherConstructors)

src/main/java/org/takes/facets/auth/social/PsGoogle.java, src/test/java/org/takes/facets/auth/social/PsGoogleTest.java
**List of changes**
- **PsGoogle**: Before try to use the json property **displayName**, the program certifies if the displayName is present in the json map, also verify if the **error** property is in the map.
- **PsGoogleTest**: Added 2 junit tests in order to test the missing of displayName property and the presence of error property in the google response.
PS: this correction is just to stop the NPE, we have to open another issue to investigate why the **displayName** is not present in the google response.
=> #623 PsGoogle throws NPE 

src/main/java/org/takes/rq/RqMultipart.java, src/main/java/org/takes/rq/TempInputStream.java, src/test/java/org/takes/rq/RqMultipartTest.java
Fix for https://github.com/yegor256/takes/issues/576
The goal of this PR is to close all the parts of the request in order to ensure that all the temporary files are properly deleted.
=> #576: Close all the parts on request's body close

src/main/java/org/takes/facets/auth/PsBasic.java, src/test/java/org/takes/facets/auth/PsBasicTest.java
#600 I moved code from constructor to separate method. I added `@SuppressWarnings("PMD.TooManyMethods")` annotation to class.
Also I added test that uses PsBasic.Default to be sure that PsBasic.Default works fine.
=> #600 PsBasic.Default constructor must only set final variables and call other constructors

src/main/java/org/takes/rq/RqLive.java
Fix for #655 
The goal of this PR is to reduce the Cyclomatic Complexity of the class RqLive by refactoring the parse method. 
Please note that I did not create a new class as expressed in the puzzle description because the class RqLive is already very simple as it only contains private static methods so creating a new class won't help in this case.
=> #655: Refactor the parse method to reduce the Cyclomatic Complexity

src/main/java/org/takes/facets/fork/FkTypes.java, src/main/java/org/takes/facets/fork/TkConsumes.java, src/main/java/org/takes/facets/fork/TkProduces.java, src/test/java/org/takes/facets/fork/FkTypesTest.java
Fix for #635 
The goal of this PR is to simplify TkProduces and TkConsumes by using TkFork instead of RsFork. For the need of this task, I added one new constructor in the class FkTypes in order to allow to provide a Take instead of a static Response. This way we can still provide a static response if we want but now we can provide a take for dynamic responses.
=> #635: Simplify TkProduces and TkConsumes by using TkFork instead of RsFork

pom.xml, src/main/java/org/takes/facets/fork/FkRegex.java, src/main/java/org/takes/http/FtCLI.java, src/main/java/org/takes/http/MainRemote.java, src/main/java/org/takes/rq/RqMultipart.java
Issue #624 - Solving puzzle 574-2964594e in pom.xml.
Fixing and removing the following 'excludes' of FindBugs in the pom.xml file:
- findbugs:org.takes.facets.fork.FkRegex$2 `SIC_INNER_SHOULD_BE_STATIC_ANON`
- findbugs:org.takes.http.FtCLI$3	`SIC_INNER_SHOULD_BE_STATIC_ANON`	
- findbugs:org.takes.http.MainRemote$1 `SIC_INNER_SHOULD_BE_STATIC_ANON`
- findbugs:org.takes.rq.RqMultipart$Base `VA_FORMAT_STRING_USES_NEWLINE`
30 minutes to implement this task. It is not enough because the problem is much bigger and requires more work than the slotted time allows. A new puzzle was created so that can be resolved by other people.
=> #624 - Removing 'excludes' of FindBuging

src/main/java/org/takes/rq/RqMultipart.java, src/test/java/org/takes/rq/RqMultipartTest.java
Fix for #626 
The goal of the PR is to improve the way to identify the boundary pattern especially when we have an empty line before the pattern. If the pattern cannot be found, we get unexpected behavior such as IOException of type "Too many open files in system" because the loop is endless so it creates and opens new files again and again.
=> #626: Improve the way to identify the boundary

src/main/java/org/takes/rq/RqMultipart.java, src/test/java/org/takes/rq/RqMultipartTest.java
Issue #625. Puzzle 620-91883c6a in src/test/java/org/takes/rq/RqMultipartTest.java:91-98. This test is using RqGreedy in order to survive. Let's remove RqGreedy from this test and three other test methods below. This PR do the following changes:
- Removes RqGreedy from RqMultipartTest.
- Refactoring 'RqMultipart.Fake.FakeMultipartRequest' to not read body() of dispositions several times. Rather that, the body is created only one time, at the constructor.
=> #625 Removing RqGreedy from RqMultipartTest.

src/main/java/org/takes/facets/fallback/FbLog4j.java, src/main/java/org/takes/facets/fallback/FbSlf4j.java, src/main/java/org/takes/http/BkBasic.java, src/main/java/org/takes/http/Options.java, src/main/java/org/takes/misc/Utf8InputStreamReader.java, src/main/java/org/takes/misc/Utf8OutputStreamWriter.java, src/main/java/org/takes/misc/Utf8PrintStream.java, src/main/java/org/takes/rq/RqPrint.java, src/main/java/org/takes/rq/multipart/RqMtFake.java, src/main/java/org/takes/rs/RsPrint.java, src/main/java/org/takes/rs/RsVelocity.java, src/main/java/org/takes/rs/RsWithBody.java, src/main/java/org/takes/rs/RsXSLT.java, src/main/java/org/takes/rs/xe/RsXembly.java, src/test/java/org/takes/rq/multipart/RqTempTest.java
Issue #674. Puzzle 664-ddd2c9b3 in src/main/java/org/takes/rs/RsXSLT.java:143-145. Removes usage of StandardCharsets.UTF_8 from takes code (remove usage not only from this class but also from other parts of project). This PR do the following changes:
- Create new classes Utf8InputStreamReader, Utf8OutputStreamWriter, Utf8PrintStream and and replaced StandardCharsets.UTF_8 usage in all takes code.
=> #674 Get rid of StandardCharsets.UTF_8.

src/main/java/org/takes/facets/fork/FkEncoding.java, src/main/java/org/takes/facets/fork/FkHost.java, src/main/java/org/takes/facets/fork/MediaType.java, src/main/java/org/takes/facets/fork/MediaTypes.java, src/main/java/org/takes/misc/EnglishLowerCase.java, src/main/java/org/takes/rq/RqCookies.java, src/main/java/org/takes/rq/RqForm.java, src/main/java/org/takes/rq/RqHeaders.java, src/main/java/org/takes/rq/RqWithoutHeader.java, src/main/java/org/takes/rq/multipart/RqMtBase.java, src/main/java/org/takes/rs/RsWithoutHeader.java, src/main/java/org/takes/tk/TkProxy.java
Issue #667. There are too many places in the code base where we call toLowerCase(Locale.ENGLISH) from a String. This PR do the following changes:
- Create new class EnglishLowerCase and replaces String#toLowerCase(Locale.ENGLISH) usage in all takes code.
- A new puzlle was created in the class org.takes.rq.RqForm.
=> #667 Removes String#toLowerCase(Locale.ENGLISH)

pom.xml, src/main/java/org/takes/HttpException.java, src/main/java/org/takes/facets/auth/codecs/CcBase64.java, src/main/java/org/takes/rq/ChunkedInputStream.java, src/main/java/org/takes/rq/RqForm.java
Issue #678. 
I removed warning, switched Qulice to version 0.16.4, added excludes to `pom.xml` to temporary ignore warnings that rises with new version of CheckStyle and PMD. Also I fixed FindBugs warnings and added 2 new puzzles.
=> Issue #678 fix. Remove warning. Use qulice 0.16.4

src/main/java/org/takes/rq/form/RqFormBase.java, src/main/java/org/takes/rq/form/RqFormFake.java, src/main/java/org/takes/rq/form/RqFormSmart.java, src/main/java/org/takes/rq/form/package-info.java, src/test/java/org/takes/facets/auth/social/PsGithubTest.java, src/test/java/org/takes/facets/auth/social/PsGoogleTest.java, src/test/java/org/takes/http/FtRemoteTest.java, src/test/java/org/takes/rq/form/RqFormBaseTest.java, src/test/java/org/takes/rq/form/RqFormFakeTest.java, src/test/java/org/takes/rq/form/RqFormSmartTest.java, src/test/java/org/takes/rq/form/package-info.java
Removed checkstyle suppression ClassDataAbstractionCouplingCheck from RqForm, but is still needed in RqFormBase.
=> Refactored RqForm into 1 interface and 3 smaller classes.

README.md
README.md implied that just configuring SLF4J was enough to get logs. In fact you need to wrap your Takes in TkSlf4j. Suggested update to the docs to make this clear.
=> Update README.md with info about TkSlf4j

src/main/java/org/takes/misc/Utf8String.java, src/main/java/org/takes/rq/form/RqFormBase.java
Issue #695. Refactor the RqFormBase class to reduce the data abstraction coupling in order to get rid of the checkstyle suppression of ClassDataAbstractionCouplingCheck. This PR do the following changes:
- Adds a englishLowerCase method to the Utf8String class;
- Refactor the RqFormBase class and removes the ClassDataAbstractionCouplingCheck checkstyle suppression;
=> Issue #695 - RqFormBase: Get rid of the checkstyle suppression of ClassDataAbstractionCouplingCheck.

README.md
I have corrected the typo in usage instruction.
=> RsHTML changed to RsHtml in readme.md

src/main/java/org/takes/facets/flash/RsFlash.java
Issue #698. After upgrade to qulice 0.16.4 we have to fix SingularField PMD warings in the RSFlash class. 
This PR do the following changes:
- Removes the SingularField PMD supression on RsFlash.java.
- Removes the lombok.ToString and override toString using the text variable
=> Issue #698 - RsFlash: Get rid of the SingularField PMD suppression

pom.xml, src/main/java/org/takes/facets/auth/codecs/CcBase64.java, src/main/java/org/takes/misc/Base64.java, src/test/java/org/takes/facets/auth/codecs/CcBase64Test.java, src/test/java/org/takes/misc/Base64Test.java
Hi.
I implemented a simple Base64 de/encoder (with tests) and used it to enable the CcBase64 codec and its tests. This is only the foundation for more thing to come, but these changes work for themselves and could thus be pulled separately. Also, bumped the version in pom.xml.
Regards, Sven
=> Base64 de/encoding

src/main/java/org/takes/facets/auth/PsToken.java, src/main/java/org/takes/facets/auth/Token.java, src/main/java/org/takes/facets/auth/signatures/SiHmac.java, src/main/java/org/takes/facets/auth/signatures/Signature.java, src/main/java/org/takes/facets/auth/signatures/package-info.java, src/test/java/org/takes/facets/auth/TokenTest.java, src/test/java/org/takes/facets/auth/signatures/SiHmacTest.java, src/test/java/org/takes/facets/auth/signatures/package-info.java
These commits introduce the following things in order to make JSON Web Token (JWT, see https://jwt.io/) usable in takes:
1. A new Signature interface, similar to the Codec interface. The main difference is that while Codecs can encrypt and decrypt data, a Signature can only encrypt (aka sign) data. 
2. An HMAC-SHA implementation of that interface with variations of 256, 384 and 512 bitlength. This is the standard signature algorithm for JWT.
2. A new interface for Token and two implementations that provide a JOSE token (JWT header) and a JWT payload token.
3. A new Pass that accepts JWT from a Bearer header and adds a new JWT to its response (obviously, that works only with JSON responses).
=> Implementation of JSON Web Token

README.md
This link was not pointing to the correct anchor tag in the README. Now it correctly takes the user to the right section.
Thanks for the project!
=> fix build & run link in README

src/main/java/org/takes/http/Back.java, src/main/java/org/takes/http/Front.java, src/main/java/org/takes/http/FtBasic.java, src/test/java/org/takes/http/FtBasicTest.java
Implementation for #373 . I decided to wrap `Back` in `FtBasic` in `BkSafe` so that default usage of `FtBasic` will be safe.
=> Response pipe broke

src/main/java/org/takes/facets/hamcrest/AbstractHmBody.java, src/main/java/org/takes/facets/hamcrest/HmRqBody.java, src/main/java/org/takes/facets/hamcrest/HmRsBody.java, src/test/java/org/takes/facets/hamcrest/HmRqBodyTest.java, src/test/java/org/takes/facets/hamcrest/HmRsBodyTest.java
=> #485 Introduce AbstractHmBody matcher and implementations

src/test/java/org/takes/http/FtRemoteTest.java, src/test/java/org/takes/tk/TkSlf4jRemoteTest.java, src/test/java/org/takes/tk/TkSlf4jTest.java
Added test cases that proves that problem is not about `TkSlf4j`, but `FtRemote` itself could not work properly with `TkEmpty`. The thing is that it prints additional things to the body, even though the response from Take is empty.
`TkSlf4j` wasn't working because in `FtBasic` the call to `input.available` returned some value, although it shouldn't. So it tries to log, what comes to him, but couldn't as it is not real request. So it works as it should be I believe, and the thing that it's failing - is a good thing. We should concentrate on issue in `FtBasic` instead.
=> #730 Problem do not relate to TkSlf4j, but to FtRemote

src/main/java/org/takes/misc/Condition.java, src/test/java/org/takes/misc/SelectTest.java
=> #780 Implement Condition.Range

src/main/java/org/takes/rs/RsPrint.java, src/test/java/org/takes/rs/RsPrintTest.java
PR for #778. Partially implemented by adding `try-finally` block for the `RsPrint.printBody()` method. The `try-finally` block works fine for `RsPrint.printBody()`, but for `RsPrint.printHead()` there should be additional work done as `OutputStreamWriter` which is used to write head contents do not call `flush()` method of `OutputStream`. Leaved puzzle to address this issue.
=> OutputStream in RsPrint may fail to flush() in case of IOException

README.md, src/main/java/org/takes/http/Back.java
Implementation for the #782. Documented the `Back` interface in `README.md`. Provided the details about all implementations in the codebase:
* `BkBasic`
* `BkParallel`
* `BkSafe`
* `BkTimeable`
* `BkWrap`
=> #782 Document Back interface in README.md

src/main/java/org/takes/facets/hamcrest/AbstractHmBody.java, src/main/java/org/takes/facets/hamcrest/AbstractHmTextBody.java, src/main/java/org/takes/facets/hamcrest/HmRqTextBody.java, src/main/java/org/takes/facets/hamcrest/HmRsTextBody.java, src/test/java/org/takes/facets/hamcrest/HmRqTextBodyTest.java, src/test/java/org/takes/facets/hamcrest/HmRsTextBodyTest.java
Fix for #794.
I've added `AbstractHmTextBody` matcher, that converts body contents to `String` and use that to match the contents with provided matcher. Added text body matchers for `Request` and `Response` with relevant test cases. 
However, there still not covered descriptions of the fails and `describeMismatchSafely` is not implemented. Left puzzle to address this issue.
This PR partially solves original issue. Left puzzle to address what was left (converting `AbstractHmBody` to `AbstractHmBytesBody`) as those are beyond 30 mins mark.
=> AbstractHmBody doesn't allow to use different matchers for text bodies

src/main/java/org/takes/facets/hamcrest/AbstractHmBody.java, src/test/java/org/takes/facets/hamcrest/HmRqBodyTest.java, src/test/java/org/takes/facets/hamcrest/HmRsBodyTest.java
Fix for #795. Improved describeTo and describeMismatchSafely so that they show the actual and expected bytes in the bodies to make it more readable.
=> HmBodyMatchers doesn't show mismatch in readable way

src/main/java/org/takes/facets/hamcrest/AbstractHmHeader.java, src/main/java/org/takes/facets/hamcrest/HmRqHeader.java, src/main/java/org/takes/facets/hamcrest/HmRsHeader.java
For #786:
- Removed constructors from `AbstractHmHeader`
- Added constructors to `HmRqHeader` and `HmRsHeader`
=> For #786: Correct HmRqHeader and HmRsHeader constructors

src/main/java/org/takes/http/BkBasic.java, src/test/java/org/takes/http/BkBasicTest.java
For #725:
- Moved fields to public constants in `FkBasic`
- Removed todo in `FkBasicTest`
=> For #725: Move header names from BkBasic to public constants

src/test/java/org/takes/http/FtRemoteTest.java
This is for #800:
- after reading previous PR #855, I confirmed that it was indeed jcabi-http that had a problem.
- I've wrote down the result of this investigation in jcabi/jcabi-http#177
- I've added a `@todo` to record those results
=> Continue investigation for #800

src/main/java/org/takes/facets/hamcrest/AbstractHmTextBody.java, src/test/java/org/takes/facets/hamcrest/HmTextBodyTest.java
For #819 I've changed `AbstractHmTextBody` to properly describe mismatches, added corresponding test and removed `todo`.
=> #819: describe mismatch in AbstractHmTextBody

src/main/java/org/takes/facets/fork/TkMethods.java, src/test/java/org/takes/facets/fork/TkMethodsTest.java
This is for #861.
Added a test and a fix.
=> TkMethods now returns 405 on unsupported method

src/main/java/org/takes/rs/RsPrint.java, src/test/java/org/takes/rs/RsPrintTest.java
For #838 I've made `RsPrint.printBody()` close body and added corresponding test.
=> #838 close body in RsPrint

pom.xml, src/main/java/org/takes/misc/Utf8String.java, src/main/java/org/takes/rs/Body.java, src/main/java/org/takes/rs/RsPrint.java, src/test/java/org/takes/facets/hamcrest/HmTextBodyTest.java, src/test/java/org/takes/rs/RsTextTest.java, src/test/java/org/takes/rs/RsWithTypeTest.java, src/test/java/org/takes/tk/TkHtmlTest.java, src/test/java/org/takes/tk/TkRedirectTest.java, src/test/java/org/takes/tk/TkTextTest.java, src/test/java/org/takes/tk/TkWithHeadersTest.java
Toward making Takes Cactoos-compliant for #804.
This is better reviewed commit by commit.
Basically I
1. Started removing uses of Guava as proposed by ARC (see https://github.com/yegor256/takes/issues/804#issuecomment-439715270) by:
1. Used `JoinedText` and `cactoos-matchers` in tests
2. Made `RsPrint` Cactoos-compliant to to be able to write those tests
3. Added a `@todo` to continue this task and more towards Cactoos compliance
2. Added two `@todos` that also go into this direction and that were blockers for me to rewrite tests and remove Guava.
I'm sure more `@todo`s could have been written but I think that's a good start.
=> Start using Cactoos

pom.xml, src/main/java/org/takes/rs/RsVelocity.java
For #842 I've migrated to velocity 2.0. For more details check #842.
=> #842 migrated to velocity 2.0

pom.xml, src/test/java/org/takes/facets/auth/social/PsFacebookTest.java
#876 
* corrected test for PsFacebook to generate correct unicode characters (and not control sequences - `random()` was generating those and that's why the test was sometimes failing)
=> #876 corrected test for PsFacebook

pom.xml
For #877 removed junit-platform-surefire-provider and redundant junit-jupter-engine from pom.xml.
=> For #877 removed junit-platform-surefire-provider 

pom.xml, src/main/java/org/takes/facets/auth/PsToken.java, src/main/java/org/takes/facets/auth/Token.java, src/main/java/org/takes/facets/auth/signatures/SiHmac.java, src/main/java/org/takes/facets/fork/FkHitRefresh.java, src/main/java/org/takes/facets/forward/RsForward.java, src/main/java/org/takes/facets/forward/TkForward.java, src/main/java/org/takes/misc/Expires.java, src/main/java/org/takes/rq/form/RqFormBase.java, src/main/java/org/takes/rs/RsGzip.java, src/main/java/org/takes/rs/RsPrettyJson.java
#882 
- `Charset.defaultCharset()` as default encoding to strings
- Hard coded pathname fixed
- `RsForward` serialization fixed
=> #882 Un-exclude findbugs from qulice checks

src/test/java/org/takes/facets/auth/IdentityTest.java, src/test/java/org/takes/facets/auth/PsAllTest.java, src/test/java/org/takes/facets/auth/PsBasicDefaultTest.java, src/test/java/org/takes/facets/auth/PsChainTest.java, src/test/java/org/takes/facets/hamcrest/HmBodyTest.java, src/test/java/org/takes/facets/hamcrest/HmRqTextBodyTest.java, src/test/java/org/takes/facets/hamcrest/HmRsStatusTest.java, src/test/java/org/takes/facets/hamcrest/HmRsTextBodyTest.java
For PF #893:
Removed the static Matchers from some classes.
=> #893 Removed the static Matchers from some classes

src/test/java/org/takes/rq/multipart/RqMtFakeTest.java
This adds a simplified testcase for the problem described in #577 
A puzzle tracks the completion of the actual fix.
=> Add reproducer for #577

src/main/java/org/takes/servlet/HttpServletRequestFake.java, src/main/java/org/takes/servlet/RqFrom.java, src/main/java/org/takes/servlet/ServletInputStreamOf.java, src/main/java/org/takes/servlet/SrvTake.java, src/test/java/org/takes/servlet/HttpServletRequestFakeTest.java, src/test/java/org/takes/servlet/RqFromTest.java
As per #865. Created:
- `RqFromTest`
- `HttpServletRequestFake` and `ServletInputStreamOf` to support it
- `HttpServletResquetFakTest`
=> #865 Added RqFromTest and HttpServletRequestFake

status-reports/2019-01-26.md
=> Project report - 2019-01-26.

src/main/java/org/takes/rs/RsPrint.java, src/test/java/org/takes/facets/cookies/RsWithCookieTest.java, src/test/java/org/takes/facets/fork/FkChainTest.java, src/test/java/org/takes/facets/fork/TkConsumesTest.java, src/test/java/org/takes/facets/fork/TkForkTest.java, src/test/java/org/takes/facets/fork/TkProducesTest.java, src/test/java/org/takes/http/BkBasicTest.java, src/test/java/org/takes/misc/ConcatTest.java, src/test/java/org/takes/misc/TransformTest.java, src/test/java/org/takes/rq/ChunkedInputStreamTest.java, src/test/java/org/takes/rq/RqChunkTest.java, src/test/java/org/takes/rq/RqGreedyTest.java, src/test/java/org/takes/rq/multipart/RqMtBaseTest.java, src/test/java/org/takes/rq/multipart/RqMtSmartTest.java
In this PR I replaced several occurences of Joiner with JoinedText. See #888
I intentionally did not touch the other idiomatic problems in the tests cases.
I left a puzzle that describes the tasks that still have to be done.
=> Update tests to replace guava with cactoos #888

src/main/java/org/takes/rs/RsEmpty.java, src/main/java/org/takes/rs/RsHtml.java, src/main/java/org/takes/rs/RsText.java, src/main/java/org/takes/rs/RsWithBody.java, src/test/java/org/takes/facets/auth/PsChainTest.java, src/test/java/org/takes/facets/cookies/RsWithCookieTest.java, src/test/java/org/takes/facets/hamcrest/HmRsStatusTest.java, src/test/java/org/takes/rs/RsWithHeaderTest.java, src/test/java/org/takes/rs/RsWithHeadersTest.java, src/test/java/org/takes/rs/RsWithTypeTest.java, src/test/java/org/takes/rs/RsWithoutHeaderTest.java, src/test/java/org/takes/tk/TkWithHeadersTest.java
#952 suggests to change the status code from `RsEmpty` from `200` to `204`. This breaks ~60 test cases which rely on `RsEmpty returning` 200.
I had to edit a few classes that add content to the Response so that the status code is the expected (and correct) 200. I also had to edit a few tests that expected a 200 status code while 204 is the correct one.
=> Introduce RsSmartNotEmpty #952

pom.xml
This is for https://github.com/yegor256/takes/issues/976.
In this PR:
- maven-compiler-plugin updated to 3.8.0
- `useIncrementalCompilation` set to `false` to allow incremental compilation :) (see [this](https://stackoverflow.com/questions/16963012/maven-compiler-recompile-all-files-instead-modified/19653164#19653164))
=> (#976) Update maven-compiler-plugin and fix bug on it to allow incremental compilation

.travis.yml
For #980 
- Updated ruby version to 2.6.0
=> #980. Update ruby version to 2.6.0

pom.xml, src/main/java/org/takes/rs/RsPrint.java, src/test/java/org/takes/facets/auth/PsBasicTest.java, src/test/java/org/takes/facets/auth/PsCookieTest.java, src/test/java/org/takes/facets/auth/TkAuthTest.java, src/test/java/org/takes/facets/cookies/RsWithCookieTest.java, src/test/java/org/takes/facets/cookies/TkJoinedCookiesTest.java, src/test/java/org/takes/facets/flash/RsFlashTest.java, src/test/java/org/takes/rs/RsWithStatusTest.java, src/test/java/org/takes/rs/RsWithoutHeaderTest.java
For #968
- Updated cactoos-matchers to 0.15
- Replaced Guava's code on cactoos
- Replaced static matchers on cactoos-matchers
- Updated puzzle
=> For #968. Removing Guava's code.

src/main/java/org/takes/facets/fork/FkRegex.java, src/test/java/org/takes/facets/fork/FkRegexTest.java
For: #990
- Added a fluent setter for disabling the removal of the trailing slash
`new FkRegEx().setRemoveTrailingSlash(false)`
- Removing the trailing slash is still the default
- Extended FkRegex component test
=> For #990: Added support for keeping trailing slashes in FkRegex.

src/main/java/org/takes/rs/RsWithStatus.java, src/test/java/org/takes/rs/RsWithTypeTest.java, src/test/java/org/takes/tk/TkRedirectTest.java
* Added missing HTTP status codes (203, 205, 206, 300, 407, 409, 503, 504, 505)
* Status codes descriptions updated according to [RFC7231](https://tools.ietf.org/html/rfc7231) e.g. HTTP 302 is now "Found" instead of "Moved temporarily"
* Status codes ordered ascending so it's easier to visually find particular code
=> Update http status codes and descriptions

src/main/java/org/takes/facets/auth/PsToken.java, src/main/java/org/takes/package-info.java, src/main/java/org/takes/rq/RqWithoutHeader.java, src/main/java/org/takes/rq/multipart/RqMtBase.java, src/main/java/org/takes/rs/RsWithStatus.java, src/main/java/org/takes/rs/RsWithoutHeader.java, src/main/java/org/takes/servlet/HttpServletResponseFake.java
=> (#1011) Replaced String.startsWith by cactoos scalar StartsWith

src/main/java/org/takes/facets/fork/FkHost.java
=> (#1019) Simplified conditional statement with EO way

README.md
Hello,
When you visit the repository link in the current readme you will get the following error:
```
501 HTTPS Required. 
Use https://repo1.maven.org/maven2/
More information at https://links.sonatype.com/central/501-https-required
```
So I changed the URL accordingly.
=> Use https instead of http for the maven takes repository

src/main/java/org/takes/http/BkBasic.java, src/test/java/org/takes/http/BkBasicTest.java
The remote **port** of requests - which _takes_ adds as a custom http header - was set using the key of the remote **address**. This simple change fixes that. Test assertions have been added to make sure the exception described at #1060 is fixed.
A new version of _takes_ in maven that includes this PR would be awesome!
=> #1060 fix exception in RqSocket.getRemotePort()

src/main/java/org/takes/rq/RqOnce.java, src/test/java/org/takes/rq/RqOnceTest.java
Per #999:
- Make `RqOnce` use `Sticky`
=> #999: Use `scalar.Sticky` for caching request

src/main/java/org/takes/http/BkBasic.java, src/main/java/org/takes/rs/BodyPrint.java, src/main/java/org/takes/rs/HeadPrint.java, src/main/java/org/takes/rs/RsPrint.java, src/test/java/org/takes/facets/auth/PsBasicTest.java, src/test/java/org/takes/facets/fallback/FbChainTest.java, src/test/java/org/takes/facets/fallback/FbStatusTest.java, src/test/java/org/takes/facets/fallback/TkFallbackTest.java, src/test/java/org/takes/facets/fork/RsForkTest.java, src/test/java/org/takes/rs/BodyPrintTest.java, src/test/java/org/takes/rs/HeadPrintTest.java, src/test/java/org/takes/rs/RsGzipTest.java, src/test/java/org/takes/rs/RsPrettyJsonTest.java, src/test/java/org/takes/rs/RsPrettyXmlTest.java, src/test/java/org/takes/rs/RsPrintTest.java, src/test/java/org/takes/rs/RsTextTest.java, src/test/java/org/takes/tk/TkClasspathTest.java, src/test/java/org/takes/tk/TkCorsTest.java, src/test/java/org/takes/tk/TkFilesTest.java, src/test/java/org/takes/tk/TkProxyTest.java
For #1074, #1075
- Remove print methods from RsPrint, HeadPrint and BodyPrint
- Introduce test for HeadPrint and BodyPrint
=> (#1074, #1075) Refactor RsPrint and introduce tests for HeadPrint and BodyPrint

src/test/java/org/takes/misc/HrefTest.java
For #975 
- Introduce a test for query params in `HrefTest`
Documentation has been already fixed.
=> (#975) Introduce query params test in HrefTest

appveyor.yml
AppVeyor CI used a broken link of maven. We updated it
with the correct one.
Ref: #1111
=> fix(maven): change maven link

src/main/java/org/takes/facets/auth/social/PsGithub.java
Now, Github only allows sending token in the header. We fixed it.
See: https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/
Fix: #1118
=> fix(github): fix deprecating auth through query param

pom.xml
There was a bug on missing version while releasing with rultor.
Ref: https://github.com/yegor256/takes/pull/1120#issuecomment-1140376155
=> build(dev-deps): set version of duplicate-finder-maven-plugin to 1.5.1

.rultor.yml
It is to fix sonar error about link not found while releasing with Rultor.
Ref: https://github.com/yegor256/takes/pull/1123#issuecomment-1141056834
=> ci(rultor): remove sonar checks in release command

src/main/java/org/takes/facets/auth/PsBasic.java, src/main/java/org/takes/facets/fork/FkHost.java, src/main/java/org/takes/rq/RqSocket.java, src/main/java/org/takes/rq/multipart/RqMtFake.java, src/main/java/org/takes/tk/TkCors.java, src/main/java/org/takes/tk/TkSslOnly.java, src/test/java/org/takes/http/BkBasicTest.java, src/test/java/org/takes/rq/RqHeadersTest.java
Remove unnecessary `new RqHeaders.Base(req)` calls if we construct `RqHeaders.Smart`.
=> Construct RqHeaders.Smart from Request

src/main/java/org/takes/rs/xe/XeSla.java
Make `XeSla` explicitly use US locale in `String.format` for proper decimal separator.
Closes #1215
=> XeSla decimal formatting fixed

src/main/java/org/takes/rq/RqLengthAware.java, src/test/java/org/takes/rq/RqLengthAwareTest.java
Currently RqLengthAware uses the InputStream#available to cap the input if no Content-Length header is given, but the return value does not say anything about the real content length, only how many bytes can be read without blocking (what might be 0).
This now only returns a CapInputStream when a Content-Length is given in the request.
Fixes https://github.com/yegor256/takes/issues/1301
=> Only cap the input if content length header is given

src/test/java/org/takes/tk/TkProxyTest.java
@yegor256 Hi, please review! This should fix the build.
=> fixing a broken build

src/main/java/org/takes/rq/ChunkedInputStream.java, src/test/java/org/takes/rq/ChunkedInputStreamTest.java
=> Issue 1303 solved.

src/main/java/org/takes/rq/CapInputStream.java, src/test/java/org/takes/rq/CapInputStreamTest.java
@yegor256, after reviewing code of CapInputStream i found possible mistake in logic. There we have skip function, which skips buffer, however this class is different from InputStream because of its cap. So by logic, skipping something should also change cap. So i ran all tests written before me with my changes of code, they all went good, and i created my own test, that checks one simple case:
we have stream and cap of 50
we skip 75, it should skip 50, since the cap is 50, and also it should decrease "more" variable, which represents how much we can read at that point and not violate cap.
=> Changed CapInputStream
